// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/demo-course/page.tsx
{
  const handler = {} as typeof import("../../src/app/demo-course/page.js")
  handler satisfies AppPageConfig<"/demo-course">
}

// Validate ../../src/app/demo-enhanced/page.tsx
{
  const handler = {} as typeof import("../../src/app/demo-enhanced/page.js")
  handler satisfies AppPageConfig<"/demo-enhanced">
}

// Validate ../../src/app/demo-simple/page.tsx
{
  const handler = {} as typeof import("../../src/app/demo-simple/page.js")
  handler satisfies AppPageConfig<"/demo-simple">
}

// Validate ../../src/app/demo-wallet/page.tsx
{
  const handler = {} as typeof import("../../src/app/demo-wallet/page.js")
  handler satisfies AppPageConfig<"/demo-wallet">
}

// Validate ../../src/app/page.tsx
{
  const handler = {} as typeof import("../../src/app/page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ../../src/app/planning/page.tsx
{
  const handler = {} as typeof import("../../src/app/planning/page.js")
  handler satisfies AppPageConfig<"/planning">
}

// Validate ../../src/app/staircase-demo/page.tsx
{
  const handler = {} as typeof import("../../src/app/staircase-demo/page.js")
  handler satisfies AppPageConfig<"/staircase-demo">
}

// Validate ../../src/app/test-simple/page.tsx
{
  const handler = {} as typeof import("../../src/app/test-simple/page.js")
  handler satisfies AppPageConfig<"/test-simple">
}

// Validate ../../src/app/test/page.tsx
{
  const handler = {} as typeof import("../../src/app/test/page.js")
  handler satisfies AppPageConfig<"/test">
}







// Validate ../../src/app/layout.tsx
{
  const handler = {} as typeof import("../../src/app/layout.js")
  handler satisfies LayoutConfig<"/">
}
